#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}



PROCESS=manage_my_process
PIDFILE=/var/run/my_process.pid

start() {
  if [ -f "$PIDFILE" ]; then
    echo "$PROCESS is already running"
    exit 1
  fi

  $PROCESS &
  echo $! > $PIDFILE
  echo "$PROCESS started"
}

stop() {
  if [ ! -f "$PIDFILE" ]; then
    echo "$PROCESS is not running"
    exit 1
  fi

  kill $(cat $PIDFILE)
  rm $PIDFILE
  echo "$PROCESS stopped"
}

restart() {
  stop
  start
  echo "$PROCESS restarted"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac




